apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: starbucks
    app.kubernetes.io/instance: starbucks
  name: starbucks
  namespace: starbucks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starbucks
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
        - image: ranjandalai4049/starbucks:latest
          name: starbucks
          ports:
            - containerPort: 8080
