apiVersion: v1
kind: Service
metadata:
  labels:
    app: starbucks
    app.kubernetes.io/instance: starbucks
  name: starbucks
  namespace: starbucks
spec:
  ports:
    - nodePort: 30001
      port: 8080
      targetPort: 8080
  selector:
    app: starbucks
  type: NodePort
